name: Build project

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install conan
      shell: bash
      run: |
        pip install conan --upgrade --user

    - name: Verify has profile
      shell: bash
      run: |
        conan profile detect || echo "Already has default profile"

    - name: Install dependencies
      shell: bash
      run: |
        echo "Installing dependencies..."
        conan install . --build=missing

    - name: Build the project
      shell: bash
      run: |
        echo "Building the porject..."
        conan build .
